"""empty message

Revision ID: 148ebcd7ded3
Revises: 
Create Date: 2021-11-06 11:14:14.766917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148ebcd7ded3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('level', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_student_level'), 'student', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_level'), table_name='student')
    op.drop_column('student', 'level')
    # ### end Alembic commands ###
