"""empty message

Revision ID: 1a4c33e034aa
Revises: f328c033f429
Create Date: 2021-11-10 07:55:24.268665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4c33e034aa'
down_revision = 'f328c033f429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_back', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feed_back', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feed_back', type_='foreignkey')
    op.drop_column('feed_back', 'student_id')
    # ### end Alembic commands ###
