"""empty message

Revision ID: 389b419bda14
Revises: 122be5169264
Create Date: 2021-11-15 19:30:19.354195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389b419bda14'
down_revision = '122be5169264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_log', sa.Column('student_msg', sa.Text(), nullable=True))
    op.add_column('chat_log', sa.Column('bot_msg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_log', 'bot_msg')
    op.drop_column('chat_log', 'student_msg')
    # ### end Alembic commands ###
