"""empty message

Revision ID: 3a818309fd44
Revises: 1a4c33e034aa
Create Date: 2021-11-10 08:00:29.531477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a818309fd44'
down_revision = '1a4c33e034aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_back', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_back', 'read')
    # ### end Alembic commands ###
