"""empty message

Revision ID: 7bca24d77737
Revises: 148ebcd7ded3
Create Date: 2021-11-09 18:59:26.237547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bca24d77737'
down_revision = '148ebcd7ded3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('admin_id', sa.String(length=200), nullable=False))
    op.drop_index('ix_admin_email', table_name='admin')
    op.create_index(op.f('ix_admin_admin_id'), 'admin', ['admin_id'], unique=False)
    op.drop_column('admin', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_admin_admin_id'), table_name='admin')
    op.create_index('ix_admin_email', 'admin', ['email'], unique=False)
    op.drop_column('admin', 'admin_id')
    # ### end Alembic commands ###
